kind: Service                             
apiVersion: v1
metadata:
  name: project
  labels:
    app: project
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: project                    
  type: LoadBalancer                   