kind: Service                             
apiVersion: v1
metadata:
  name: mrdevops
  labels:
    app: mrdevops
spec:
  type: nodePort
  selector:
    app: mrdevops
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200                   
  # type: LoadBalancer                   